  networks:
    weather_net:
      name: weather_net
  services:
    postgres_weather:
      mem_limit: 512m
      cpus: 1.0
      networks: 
        - weather_net
      image: postgres:15
      container_name: weather_data
      restart: unless-stopped
      environment:
        POSTGRES_USER: "${POSTGRES_USER}"
        POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        POSTGRES_DB: "${POSTGRES_DB}"
      ports:
        - "5433:5432"
      volumes:
        - weather_postgre_data:/var/lib/postgresql/data 
        - ./init:/docker-entrypoint-initdb.d
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
        interval: 5s
        timeout: 5s
        retries: 5
    
    postgres_airflow:
      mem_limit: 512m
      cpus: 1.0
      networks: 
        - weather_net
      image: postgres:15
      container_name: airflow_metadata
      restart: unless-stopped
      environment:
        POSTGRES_USER: "${AIRFLOW_POSTGRES_USER}"
        POSTGRES_PASSWORD: "${AIRFLOW_POSTGRES_PASSWORD}"
        POSTGRES_DB: "${AIRFLOW_POSTGRES_DB}"
      volumes:
        - airflow_postgres_data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${AIRFLOW_POSTGRES_USER} -d ${AIRFLOW_POSTGRES_DB}"]   # <-- add -d airflow_db
        interval: 5s
        timeout: 5s
        retries: 5
        
    airflow:
      mem_limit: 2g
      cpus: 2.0
      networks: 
        - weather_net
      build: .              
      container_name: airflow
      stop_grace_period: 30s
      restart: unless-stopped
      user: "${AIRFLOW_UID}:0"   
      depends_on:
        postgres_airflow:
          condition: service_healthy
        postgres_weather:
          condition: service_healthy
      environment:
        AIRFLOW__CORE__EXECUTOR: LocalExecutor
        AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_POSTGRES_USER}:${AIRFLOW_POSTGRES_PASSWORD}@postgres_airflow/${AIRFLOW_POSTGRES_DB}
        AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
        DBT_PROFILES_DIR: /opt/airflow/weather_dbt
        _AIRFLOW_WWW_USER_USERNAME: "${_AIRFLOW_WWW_USER_USERNAME}"
        _AIRFLOW_WWW_USER_PASSWORD: "${_AIRFLOW_WWW_USER_PASSWORD}"
      
      ports:
        - "8080:8080"
      volumes:
        - ./dags:/opt/airflow/dags
        - ./logs:/opt/airflow/logs
        - ./scripts:/opt/airflow/scripts
        - ./weather_dbt:/opt/airflow/weather_dbt
      command: standalone
      healthcheck:
        test: ["CMD-SHELL", "curl --fail http://localhost:8080/health || exit 1"]
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 60s
    
    metabase:
      mem_limit: 1g
      cpus: 1.0
      networks: 
        - weather_net
      image: metabase/metabase:v0.51.4
      container_name: metabase_app
      restart: unless-stopped
      ports:
        - "3000:3000"
      depends_on:
        postgres_weather:
          condition: service_healthy # Waits for your pg_isready healthcheck to pass
      environment:
        MB_DB_TYPE: postgres
        MB_DB_DBNAME: "${MB_DB_DBNAME}"
        MB_DB_PORT: "${MB_DB_PORT}"
        MB_DB_USER: "${MB_DB_USER}"
        MB_DB_PASS: "${MB_DB_PASS}"
        MB_DB_HOST: "${MB_DB_HOST}"
      healthcheck:
        test: ["CMD-SHELL", "curl --fail http://localhost:3000/api/health || exit 1"]
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 60s
    
  volumes:
    weather_postgre_data:
    airflow_postgres_data: